"""
Constants for REPACSS Power Measurement
"""

from .nodes import *
from .metrics import *

__all__ = [
    # Node lists
    'IRC_NODES', 'PDU_NODES',
    'RACK_91_COMPUTE_NODES', 'RACK_91_PD_NODES',
    'RACK_92_COMPUTE_NODES', 'RACK_92_PD_NODES', 
    'RACK_93_COMPUTE_NODES', 'RACK_93_PD_NODES',
    'RACK_94_COMPUTE_NODES', 'RACK_94_PD_NODES',
    'RACK_95_COMPUTE_NODES', 'RACK_95_PD_NODES',
    'RACK_96_COMPUTE_NODES', 'RACK_96_PD_NODES',
    'RACK_97_COMPUTE_NODES', 'RACK_97_PDU_NODES',
    
    # Metrics
    'IRC_POWER_METRICS', 'IRC_ALL_METRICS', 'PDU_POWER_METRICS',
    'EXCLUDED_METRICS', 'DERIVED_METRICS'
]
